In [1]:
import pandas as pd

In [3]:
employee_fname = ['Tom','Sue','Bob','Fred','Wilma']
employee_lname = ['Smith', 'Charles','Catt','Flinstone','Rubble']
employee_age = [18,45,35,55,53]

employee_data = {
    'fname': ['Tom','Sue','Bob','Fred','Wilma'],
    'lname' :['Smith', 'Charles','Catt','Flinstone','Rubble'],
    'age' : [18,45,35,55,53]
}

employee_data

{'fname': ['Tom', 'Sue', 'Bob', 'Fred', 'Wilma'],
 'lname': ['Smith', 'Charles', 'Catt', 'Flinstone', 'Rubble'],
 'age': [18, 45, 35, 55, 53]}

In [4]:
df_series = pd.Series(employee_age)
df_series

0    18
1    45
2    35
3    55
4    53
dtype: int64

In [5]:
print(df_series.agg(['mean']))

mean    41.2
dtype: float64

In [6]:
df_series.mean()

41.2

In [7]:
df_series.to_csv('challenge4_series.csv')

In [11]:
#part 2 MLB analysis
mlb = pd.read_csv('21st century MLB Batting.csv')
print(mlb.head(5))
print(mlb.tail(6))

    playerID  yearID  stint teamID lgID    G   AB    R    H  2B  3B  HR  RBI  \
0  abbotje01    2000      1    CHA   AL   80  215   31   59  15   1   3   29
1  abbotku01    2000      1    NYN   NL   79  157   22   34   7   1   6   12
2  abbotpa01    2000      1    SEA   AL   35    5    1    2   1   0   0    0
3  abreubo01    2000      1    PHI   NL  154  576  103  182  42  10  25   79
4  aceveju01    2000      1    MIL   NL   62    1    1    0   0   0   0    0

   SB  CS   BB   SO
0   2   1   21   38
1   1   1   14   51
2   0   0    0    1
3  28   8  100  116
4   0   0    1    1
        playerID  yearID  stint teamID lgID   G   AB   R   H  2B  3B  HR  RBI  \
28157  zimmebr01    2019      1    CLE   AL   9   13   1   0   0   0   0    0
28158  zimmejo02    2019      1    DET   AL  23    2   0   0   0   0   0    0
28159  zimmeky01    2019      1    KCA   AL  15    0   0   0   0   0   0    0
28160  zimmery01    2019      1    WAS   NL  52  171  20  44   9   0   6   27
28161  zobribe01    2019      1    CHN   NL  47  150  24  39   5   0   1   17
28162  zuninmi01    2019      1    TBA   AL  90  266  30  44  10   1   9   32

       SB  CS  BB  SO
28157   0   0   1   7
28158   0   0   0   2
28159   0   0   0   0
28160   0   0  17  39
28161   0   0  23  24
28162   0   0  20  98

In [14]:
mlb['HR'].mean()

3.695593509214217

In [15]:
mlb['HR'].agg(['mean'])

mean    3.695594
Name: HR, dtype: float64

In [16]:
mlb['SO'].max()

223

In [17]:
mlb['SO'].agg(['max'])

max    223
Name: SO, dtype: int64

In [18]:
mlb.to_excel('mlb_batting.xlsx')

In [21]:
top_40 = mlb.query('HR > 40')
top_40.head(5)

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO
55,bagweje01,2000,1,HOU,NL,159,590,152,183,37,1,47,132,9,6,107,116
72,batisto01,2000,1,TOR,AL,154,620,96,163,32,2,41,114,5,4,35,121
127,bondsba01,2000,1,SFN,NL,143,480,129,147,28,4,49,106,11,3,117,77
300,delgaca01,2000,1,TOR,AL,162,569,115,196,57,1,41,137,0,1,123,104
341,edmonji01,2000,1,SLN,NL,152,525,129,155,25,0,42,108,10,3,103,167

In [22]:
top_40_2 = mlb[mlb.HR > 40]
top_40_2.head(5)

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO
55,bagweje01,2000,1,HOU,NL,159,590,152,183,37,1,47,132,9,6,107,116
72,batisto01,2000,1,TOR,AL,154,620,96,163,32,2,41,114,5,4,35,121
127,bondsba01,2000,1,SFN,NL,143,480,129,147,28,4,49,106,11,3,117,77
300,delgaca01,2000,1,TOR,AL,162,569,115,196,57,1,41,137,0,1,123,104
341,edmonji01,2000,1,SLN,NL,152,525,129,155,25,0,42,108,10,3,103,167

In [25]:
mlb.to_json('mlb_json.json', orient='split')

In [28]:
mlb_json = pd.read_json('mlb_json.json', orient='index')
mlb_json.head(5)

,0,1,2,3,4,5,6,7,8,9,...,28153,28154,28155,28156,28157,28158,28159,28160,28161,28162
columns,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,None,None,None,None,None,None,None,None,None,None
index,0,1,2,3,4,5,6,7,8,9,...,28153,28154,28155,28156,28157,28158,28159,28160,28161,28162
data,"[abbotje01, 2000, 1, CHA, AL, 80, 215, 31, 59,...","[abbotku01, 2000, 1, NYN, NL, 79, 157, 22, 34,...","[abbotpa01, 2000, 1, SEA, AL, 35, 5, 1, 2, 1, ...","[abreubo01, 2000, 1, PHI, NL, 154, 576, 103, 1...","[aceveju01, 2000, 1, MIL, NL, 62, 1, 1, 0, 0, ...","[adamste01, 2000, 1, LAN, NL, 66, 2, 0, 0, 0, ...","[agbaybe01, 2000, 1, NYN, NL, 119, 350, 59, 10...","[aguilri01, 2000, 1, CHN, NL, 54, 0, 0, 0, 0, ...","[alcanis01, 2000, 1, BOS, AL, 21, 45, 9, 13, 1...","[aldresc01, 2000, 1, PHI, NL, 23, 0, 0, 0, 0, ...",...,"[zagunma01, 2019, 1, CHN, NL, 30, 36, 2, 9, 3,...","[zamorda01, 2019, 1, NYN, NL, 17, 0, 0, 0, 0, ...","[zavalse01, 2019, 1, CHA, AL, 5, 12, 1, 1, 0, ...","[zeuchtj01, 2019, 1, TOR, AL, 5, 1, 0, 0, 0, 0...","[zimmebr01, 2019, 1, CLE, AL, 9, 13, 1, 0, 0, ...","[zimmejo02, 2019, 1, DET, AL, 23, 2, 0, 0, 0, ...","[zimmeky01, 2019, 1, KCA, AL, 15, 0, 0, 0, 0, ...","[zimmery01, 2019, 1, WAS, NL, 52, 171, 20, 44,...","[zobribe01, 2019, 1, CHN, NL, 47, 150, 24, 39,...","[zuninmi01, 2019, 1, TBA, AL, 90, 266, 30, 44,..."

In [2]:
#challenge 5
iris = pd.read_csv('iris_dirty.csv')
iris.head(10)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          NaN  Setosa
1           4.9          3.0           1.4          NaN  Setosa
2           4.7          3.2           1.3          NaN  Setosa
3           4.6          3.1           1.5          NaN  Setosa
4           5.0          3.6           1.4          NaN  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [30]:
#remove just the rows that are missing
iris2= iris.dropna()
iris2.head(10)

    sepal.length  sepal.width  petal.length  petal.width variety
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa

In [31]:
print(iris.info())
print(len(iris))
print(iris.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  153 non-null    float64
 1   sepal.width   153 non-null    float64
 2   petal.length  153 non-null    float64
 3   petal.width   148 non-null    float64
 4   variety       153 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.1+ KB
None
153
(153, 5)

In [32]:
iris3 = iris.drop(columns=['petal.width'])
iris3

     sepal.length  sepal.width  petal.length    variety
0             5.1          3.5           1.4     Setosa
1             4.9          3.0           1.4     Setosa
2             4.7          3.2           1.3     Setosa
3             4.6          3.1           1.5     Setosa
4             5.0          3.6           1.4     Setosa
..            ...          ...           ...        ...
148           6.2          3.4           5.4  Virginica
149           5.9          3.0           5.1  Virginica
150           5.9          3.0           5.1  Virginica
151           5.9          3.0           5.1  Virginica
152           5.9          3.0           5.1  Virginica

[153 rows x 4 columns]

In [3]:
setosa = iris.query("variety == 'Setosa'")
print(setosa.head(10))

setosa_avg_petal = setosa['petal.width'].mean()
setosa_avg_petal
iris ['petal.width'] = iris['petal.width'].fillna(setosa_avg_petal) 
iris.head(10)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          NaN  Setosa
1           4.9          3.0           1.4          NaN  Setosa
2           4.7          3.2           1.3          NaN  Setosa
3           4.6          3.1           1.5          NaN  Setosa
4           5.0          3.6           1.4          NaN  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4     0.251111  Setosa
1           4.9          3.0           1.4     0.251111  Setosa
2           4.7          3.2           1.3     0.251111  Setosa
3           4.6          3.1           1.5     0.251111  Setosa
4           5.0          3.6           1.4     0.251111  Setosa
5           5.4          3.9           1.7     0.400000  Setosa
6           4.6          3.4           1.4     0.300000  Setosa
7           5.0          3.4           1.5     0.200000  Setosa
8           4.4          2.9           1.4     0.200000  Setosa
9           4.9          3.1           1.5     0.100000  Setosa

In [53]:
iris.duplicated()
iris.duplicated().sum()

4

In [47]:
pd.set_option('display.max_rows', None)

In [51]:
iris5 = iris
iris5 = iris5.drop_duplicates()
len(iris5)

149

In [52]:
variety_map = {
    'Setosa': 'Setosa',
    'versicolor': 'Not Setosa',
    'Virginica':'Not Setosa'
}
iris['IsSetosa'] = iris['variety'].map(variety_map)
iris

,sepal.length,sepal.width,petal.length,petal.width,variety,IsSetosa
0,5.1,3.5,1.4,0.251111,Setosa,Setosa
1,4.9,3.0,1.4,0.251111,Setosa,Setosa
2,4.7,3.2,1.3,0.251111,Setosa,Setosa
3,4.6,3.1,1.5,0.251111,Setosa,Setosa
4,5.0,3.6,1.4,0.251111,Setosa,Setosa
5,5.4,3.9,1.7,0.400000,Setosa,Setosa
6,4.6,3.4,1.4,0.300000,Setosa,Setosa
7,5.0,3.4,1.5,0.200000,Setosa,Setosa
8,4.4,2.9,1.4,0.200000,Setosa,Setosa
9,4.9,3.1,1.5,0.100000,Setosa,Setosa
10,5.4,3.7,1.5,0.200000,Setosa,Setosa
11,4.8,3.4,1.6,0.200000,Setosa,Setosa
12,4.8,3.0,1.4,0.100000,Setosa,Setosa
13,4.3,3.0,1.1,0.100000,Setosa,Setosa
14,5.8,4.0,1.2,0.200000,Setosa,Setosa
15,5.7,4.4,1.5,0.400000,Setosa,Setosa
16,5.4,3.9,1.3,0.400000,Setosa,Setosa
17,5.1,3.5,1.4,0.300000,Setosa,Setosa
18,5.7,3.8,1.7,0.300000,Setosa,Setosa
19,5.1,3.8,1.5,0.300000,Setosa,Setosa
20,5.4,3.4,1.7,0.200000,Setosa,Setosa
21,5.1,3.7,1.5,0.400000,Setosa,Setosa
22,4.6,3.6,1.0,0.200000,Setosa,Setosa
23,5.1,3.3,1.7,0.500000,Setosa,Setosa
24,4.8,3.4,1.9,0.200000,Setosa,Setosa
25,5.0,3.0,1.6,0.200000,Setosa,Setosa
26,5.0,3.4,1.6,0.400000,Setosa,Setosa
27,5.2,3.5,1.5,0.200000,Setosa,Setosa
28,5.2,3.4,1.4,0.200000,Setosa,Setosa
29,4.7,3.2,1.6,0.200000,Setosa,Setosa
30,4.8,3.1,1.6,0.200000,Setosa,Setosa
31,5.4,3.4,1.5,0.400000,Setosa,Setosa
32,5.2,4.1,1.5,0.100000,Setosa,Setosa
33,5.5,4.2,1.4,0.200000,Setosa,Setosa
34,4.9,3.1,1.5,0.200000,Setosa,Setosa
35,5.0,3.2,1.2,0.200000,Setosa,Setosa
36,5.5,3.5,1.3,0.200000,Setosa,Setosa
37,4.9,3.6,1.4,0.100000,Setosa,Setosa
38,4.4,3.0,1.3,0.200000,Setosa,Setosa
39,5.1,3.4,1.5,0.200000,Setosa,Setosa
40,5.0,3.5,1.3,0.300000,Setosa,Setosa
41,4.5,2.3,1.3,0.300000,Setosa,Setosa
42,4.4,3.2,1.3,0.200000,Setosa,Setosa
43,5.0,3.5,1.6,0.600000,Setosa,Setosa
44,5.1,3.8,1.9,0.400000,Setosa,Setosa
45,4.8,3.0,1.4,0.300000,Setosa,Setosa
46,5.1,3.8,1.6,0.200000,Setosa,Setosa
47,4.6,3.2,1.4,0.200000,Setosa,Setosa
48,5.3,3.7,1.5,0.200000,Setosa,Setosa
49,5.0,3.3,1.4,0.200000,Setosa,Setosa
50,7.0,3.2,4.7,1.400000,Versicolor,NaN
51,6.4,3.2,4.5,1.500000,Versicolor,NaN
52,6.9,3.1,4.9,1.500000,Versicolor,NaN
53,5.5,2.3,4.0,1.300000,Versicolor,NaN
54,6.5,2.8,4.6,1.500000,Versicolor,NaN
55,5.7,2.8,4.5,1.300000,Versicolor,NaN
56,6.3,3.3,4.7,1.600000,Versicolor,NaN
57,4.9,2.4,3.3,1.000000,Versicolor,NaN
58,6.6,2.9,4.6,1.300000,Versicolor,NaN
59,5.2,2.7,3.9,1.400000,Versicolor,NaN
60,5.0,2.0,3.5,1.000000,Versicolor,NaN
61,5.9,3.0,4.2,1.500000,Versicolor,NaN
62,6.0,2.2,4.0,1.000000,Versicolor,NaN
63,6.1,2.9,4.7,1.400000,Versicolor,NaN
64,5.6,2.9,3.6,1.300000,Versicolor,NaN
65,6.7,3.1,4.4,1.400000,Versicolor,NaN
66,5.6,3.0,4.5,1.500000,Versicolor,NaN
67,5.8,2.7,4.1,1.000000,Versicolor,NaN
68,6.2,2.2,4.5,1.500000,Versicolor,NaN
69,5.6,2.5,3.9,1.100000,Versicolor,NaN
70,5.9,3.2,4.8,1.800000,Versicolor,NaN
71,6.1,2.8,4.0,1.300000,Versicolor,NaN
72,6.3,2.5,4.9,1.500000,Versicolor,NaN
73,6.1,2.8,4.7,1.200000,Versicolor,NaN
74,6.4,2.9,4.3,1.300000,Versicolor,NaN
75,6.6,3.0,4.4,1.400000,Versicolor,NaN
76,6.8,2.8,4.8,1.400000,Versicolor,NaN
77,6.7,3.0,5.0,1.700000,Versicolor,NaN
78,6.0,2.9,4.5,1.500000,Versicolor,NaN
79,5.7,2.6,3.5,1.000000,Versicolor,NaN
80,5.5,2.4,3.8,1.100000,Versicolor,NaN
81,5.5,2.4,3.7,1.000000,Versicolor,NaN
82,5.8,2.7,3.9,1.200000,Versicolor,NaN
83,6.0,2.7,5.1,1.600000,Versicolor,NaN
84,5.4,3.0,4.5,1.500000,Versicolor,NaN
85,6.0,3.4,4.5,1.600000,Versicolor,NaN
86,6.7,3.1,4.7,1.500000,Versicolor,NaN
87,6.3,2.3,4.4,1.300000,Versicolor,NaN
88,5.6,3.0,4.1,1.300000,Versicolor,NaN
89,5.5,2.5,4.0,1.300000,Versicolor,NaN
90,5.5,2.6,4.4,1.200000,Versicolor,NaN
91,6.1,3.0,4.6,1.400000,Versicolor,NaN
92,5.8,2.6,4.0,1.200000,Versicolor,NaN
93,5.0,2.3,3.3,1.000000,Versicolor,NaN
94,5.6,2.7,4.2,1.300000,Versicolor,NaN
95,5.7,3.0,4.2,1.200000,Versicolor,NaN
96,5.7,2.9,4.2,1.300000,Versicolor,NaN
97,6.2,2.9,4.3,1.300000,Versicolor,NaN
98,5.1,2.5,3.0,1.100000,Versicolor,NaN
99,5.7,2.8,4.1,1.300000,Versicolor,NaN
100,6.3,3.3,6.0,2.500000,Virginica,Not Setosa
101,5.8,2.7,5.1,1.900000,Virginica,Not Setosa
102,7.1,3.0,5.9,2.100000,Virginica,Not Setosa
103,6.3,2.9,5.6,1.800000,Virginica,Not Setosa
104,6.5,3.0,5.8,2.200000,Virginica,Not Setosa
105,7.6,3.0,6.6,2.100000,Virginica,Not Setosa
106,4.9,2.5,4.5,1.700000,Virginica,Not Setosa
107,7.3,2.9,6.3,1.800000,Virginica,Not Setosa
108,6.7,2.5,5.8,1.800000,Virginica,Not Setosa
109,7.2,3.6,6.1,2.500000,Virginica,Not Setosa
110,6.5,3.2,5.1,2.000000,Virginica,Not Setosa
111,6.4,2.7,5.3,1.900000,Virginica,Not Setosa
112,6.8,3.0,5.5,2.100000,Virginica,Not Setosa
113,5.7,2.5,5.0,2.000000,Virginica,Not Setosa
114,5.8,2.8,5.1,2.400000,Virginica,Not Setosa
115,6.4,3.2,5.3,2.300000,Virginica,Not Setosa
116,6.5,3.0,5.5,1.800000,Virginica,Not Setosa
117,7.7,3.8,6.7,2.200000,Virginica,Not Setosa
118,7.7,2.6,6.9,2.300000,Virginica,Not Setosa
119,6.0,2.2,5.0,1.500000,Virginica,Not Setosa
120,6.9,3.2,5.7,2.300000,Virginica,Not Setosa
121,5.6,2.8,4.9,2.000000,Virginica,Not Setosa
122,7.7,2.8,6.7,2.000000,Virginica,Not Setosa
123,6.3,2.7,4.9,1.800000,Virginica,Not Setosa
124,6.7,3.3,5.7,2.100000,Virginica,Not Setosa
125,7.2,3.2,6.0,1.800000,Virginica,Not Setosa
126,6.2,2.8,4.8,1.800000,Virginica,Not Setosa
127,6.1,3.0,4.9,1.800000,Virginica,Not Setosa
128,6.4,2.8,5.6,2.100000,Virginica,Not Setosa
129,7.2,3.0,5.8,1.600000,Virginica,Not Setosa
130,7.4,2.8,6.1,1.900000,Virginica,Not Setosa
131,7.9,3.8,6.4,2.000000,Virginica,Not Setosa
132,6.4,2.8,5.6,2.200000,Virginica,Not Setosa
133,6.3,2.8,5.1,1.500000,Virginica,Not Setosa
134,6.1,2.6,5.6,1.400000,Virginica,Not Setosa
135,7.7,3.0,6.1,2.300000,Virginica,Not Setosa
136,6.3,3.4,5.6,2.400000,Virginica,Not Setosa
137,6.4,3.1,5.5,1.800000,Virginica,Not Setosa
138,6.0,3.0,4.8,1.800000,Virginica,Not Setosa
139,6.9,3.1,5.4,2.100000,Virginica,Not Setosa
140,6.7,3.1,5.6,2.400000,Virginica,Not Setosa
141,6.9,3.1,5.1,2.300000,Virginica,Not Setosa
142,5.8,2.7,5.1,1.900000,Virginica,Not Setosa
143,6.8,3.2,5.9,2.300000,Virginica,Not Setosa
144,6.7,3.3,5.7,2.500000,Virginica,Not Setosa
145,6.7,3.0,5.2,2.300000,Virginica,Not Setosa
146,6.3,2.5,5.0,1.900000,Virginica,Not Setosa
147,6.5,3.0,5.2,2.000000,Virginica,Not Setosa
148,6.2,3.4,5.4,2.300000,Virginica,Not Setosa
149,5.9,3.0,5.1,1.800000,Virginica,Not Setosa
150,5.9,3.0,5.1,1.800000,Virginica,Not Setosa
151,5.9,3.0,5.1,1.800000,Virginica,Not Setosa
152,5.9,3.0,5.1,1.800000,Virginica,Not Setosa

In [56]:
pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy in c:\users\stephen lucas\anaconda3\lib\site-packages (from pandasql) (1.24.3)
Requirement already satisfied: pandas in c:\users\stephen lucas\anaconda3\lib\site-packages (from pandasql) (1.5.3)
Requirement already satisfied: sqlalchemy in c:\users\stephen lucas\anaconda3\lib\site-packages (from pandasql) (1.4.39)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\stephen lucas\anaconda3\lib\site-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\stephen lucas\anaconda3\lib\site-packages (from pandas->pandasql) (2022.7)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\stephen lucas\anaconda3\lib\site-packages (from sqlalchemy->pandasql) (2.0.1)
Requirement already satisfied: six>=1.5 in c:\users\stephen lucas\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas->pandasql) (1.16.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py): started
  Building wheel for pandasql (setup.py): finished with status 'done'
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26800 sha256=28ec557f814946c16d2a13a9da9f41da19a8305a9e4ceb2534c30bc3f1b9fcd5
  Stored in directory: c:\users\stephen lucas\appdata\local\pip\cache\wheels\68\5d\a5\edc271b998f909801d7956959f699b976cc9896075dc47c153
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3
Note: you may need to restart the kernel to use updated packages.

In [4]:
from pandasql import sqldf

In [5]:
pysqldf = lambda q: sqldf(q,globals())

In [60]:
test = sqldf("Select * From iris;")
test

,sepal.length,sepal.width,petal.length,petal.width,variety,IsSetosa
0,5.1,3.5,1.4,0.251111,Setosa,Setosa
1,4.9,3.0,1.4,0.251111,Setosa,Setosa
2,4.7,3.2,1.3,0.251111,Setosa,Setosa
3,4.6,3.1,1.5,0.251111,Setosa,Setosa
4,5.0,3.6,1.4,0.251111,Setosa,Setosa
5,5.4,3.9,1.7,0.400000,Setosa,Setosa
6,4.6,3.4,1.4,0.300000,Setosa,Setosa
7,5.0,3.4,1.5,0.200000,Setosa,Setosa
8,4.4,2.9,1.4,0.200000,Setosa,Setosa
9,4.9,3.1,1.5,0.100000,Setosa,Setosa
10,5.4,3.7,1.5,0.200000,Setosa,Setosa
11,4.8,3.4,1.6,0.200000,Setosa,Setosa
12,4.8,3.0,1.4,0.100000,Setosa,Setosa
13,4.3,3.0,1.1,0.100000,Setosa,Setosa
14,5.8,4.0,1.2,0.200000,Setosa,Setosa
15,5.7,4.4,1.5,0.400000,Setosa,Setosa
16,5.4,3.9,1.3,0.400000,Setosa,Setosa
17,5.1,3.5,1.4,0.300000,Setosa,Setosa
18,5.7,3.8,1.7,0.300000,Setosa,Setosa
19,5.1,3.8,1.5,0.300000,Setosa,Setosa
20,5.4,3.4,1.7,0.200000,Setosa,Setosa
21,5.1,3.7,1.5,0.400000,Setosa,Setosa
22,4.6,3.6,1.0,0.200000,Setosa,Setosa
23,5.1,3.3,1.7,0.500000,Setosa,Setosa
24,4.8,3.4,1.9,0.200000,Setosa,Setosa
25,5.0,3.0,1.6,0.200000,Setosa,Setosa
26,5.0,3.4,1.6,0.400000,Setosa,Setosa
27,5.2,3.5,1.5,0.200000,Setosa,Setosa
28,5.2,3.4,1.4,0.200000,Setosa,Setosa
29,4.7,3.2,1.6,0.200000,Setosa,Setosa
30,4.8,3.1,1.6,0.200000,Setosa,Setosa
31,5.4,3.4,1.5,0.400000,Setosa,Setosa
32,5.2,4.1,1.5,0.100000,Setosa,Setosa
33,5.5,4.2,1.4,0.200000,Setosa,Setosa
34,4.9,3.1,1.5,0.200000,Setosa,Setosa
35,5.0,3.2,1.2,0.200000,Setosa,Setosa
36,5.5,3.5,1.3,0.200000,Setosa,Setosa
37,4.9,3.6,1.4,0.100000,Setosa,Setosa
38,4.4,3.0,1.3,0.200000,Setosa,Setosa
39,5.1,3.4,1.5,0.200000,Setosa,Setosa
40,5.0,3.5,1.3,0.300000,Setosa,Setosa
41,4.5,2.3,1.3,0.300000,Setosa,Setosa
42,4.4,3.2,1.3,0.200000,Setosa,Setosa
43,5.0,3.5,1.6,0.600000,Setosa,Setosa
44,5.1,3.8,1.9,0.400000,Setosa,Setosa
45,4.8,3.0,1.4,0.300000,Setosa,Setosa
46,5.1,3.8,1.6,0.200000,Setosa,Setosa
47,4.6,3.2,1.4,0.200000,Setosa,Setosa
48,5.3,3.7,1.5,0.200000,Setosa,Setosa
49,5.0,3.3,1.4,0.200000,Setosa,Setosa
50,7.0,3.2,4.7,1.400000,Versicolor,None
51,6.4,3.2,4.5,1.500000,Versicolor,None
52,6.9,3.1,4.9,1.500000,Versicolor,None
53,5.5,2.3,4.0,1.300000,Versicolor,None
54,6.5,2.8,4.6,1.500000,Versicolor,None
55,5.7,2.8,4.5,1.300000,Versicolor,None
56,6.3,3.3,4.7,1.600000,Versicolor,None
57,4.9,2.4,3.3,1.000000,Versicolor,None
58,6.6,2.9,4.6,1.300000,Versicolor,None
59,5.2,2.7,3.9,1.400000,Versicolor,None
60,5.0,2.0,3.5,1.000000,Versicolor,None
61,5.9,3.0,4.2,1.500000,Versicolor,None
62,6.0,2.2,4.0,1.000000,Versicolor,None
63,6.1,2.9,4.7,1.400000,Versicolor,None
64,5.6,2.9,3.6,1.300000,Versicolor,None
65,6.7,3.1,4.4,1.400000,Versicolor,None
66,5.6,3.0,4.5,1.500000,Versicolor,None
67,5.8,2.7,4.1,1.000000,Versicolor,None
68,6.2,2.2,4.5,1.500000,Versicolor,None
69,5.6,2.5,3.9,1.100000,Versicolor,None
70,5.9,3.2,4.8,1.800000,Versicolor,None
71,6.1,2.8,4.0,1.300000,Versicolor,None
72,6.3,2.5,4.9,1.500000,Versicolor,None
73,6.1,2.8,4.7,1.200000,Versicolor,None
74,6.4,2.9,4.3,1.300000,Versicolor,None
75,6.6,3.0,4.4,1.400000,Versicolor,None
76,6.8,2.8,4.8,1.400000,Versicolor,None
77,6.7,3.0,5.0,1.700000,Versicolor,None
78,6.0,2.9,4.5,1.500000,Versicolor,None
79,5.7,2.6,3.5,1.000000,Versicolor,None
80,5.5,2.4,3.8,1.100000,Versicolor,None
81,5.5,2.4,3.7,1.000000,Versicolor,None
82,5.8,2.7,3.9,1.200000,Versicolor,None
83,6.0,2.7,5.1,1.600000,Versicolor,None
84,5.4,3.0,4.5,1.500000,Versicolor,None
85,6.0,3.4,4.5,1.600000,Versicolor,None
86,6.7,3.1,4.7,1.500000,Versicolor,None
87,6.3,2.3,4.4,1.300000,Versicolor,None
88,5.6,3.0,4.1,1.300000,Versicolor,None
89,5.5,2.5,4.0,1.300000,Versicolor,None
90,5.5,2.6,4.4,1.200000,Versicolor,None
91,6.1,3.0,4.6,1.400000,Versicolor,None
92,5.8,2.6,4.0,1.200000,Versicolor,None
93,5.0,2.3,3.3,1.000000,Versicolor,None
94,5.6,2.7,4.2,1.300000,Versicolor,None
95,5.7,3.0,4.2,1.200000,Versicolor,None
96,5.7,2.9,4.2,1.300000,Versicolor,None
97,6.2,2.9,4.3,1.300000,Versicolor,None
98,5.1,2.5,3.0,1.100000,Versicolor,None
99,5.7,2.8,4.1,1.300000,Versicolor,None
100,6.3,3.3,6.0,2.500000,Virginica,Not Setosa
101,5.8,2.7,5.1,1.900000,Virginica,Not Setosa
102,7.1,3.0,5.9,2.100000,Virginica,Not Setosa
103,6.3,2.9,5.6,1.800000,Virginica,Not Setosa
104,6.5,3.0,5.8,2.200000,Virginica,Not Setosa
105,7.6,3.0,6.6,2.100000,Virginica,Not Setosa
106,4.9,2.5,4.5,1.700000,Virginica,Not Setosa
107,7.3,2.9,6.3,1.800000,Virginica,Not Setosa
108,6.7,2.5,5.8,1.800000,Virginica,Not Setosa
109,7.2,3.6,6.1,2.500000,Virginica,Not Setosa
110,6.5,3.2,5.1,2.000000,Virginica,Not Setosa
111,6.4,2.7,5.3,1.900000,Virginica,Not Setosa
112,6.8,3.0,5.5,2.100000,Virginica,Not Setosa
113,5.7,2.5,5.0,2.000000,Virginica,Not Setosa
114,5.8,2.8,5.1,2.400000,Virginica,Not Setosa
115,6.4,3.2,5.3,2.300000,Virginica,Not Setosa
116,6.5,3.0,5.5,1.800000,Virginica,Not Setosa
117,7.7,3.8,6.7,2.200000,Virginica,Not Setosa
118,7.7,2.6,6.9,2.300000,Virginica,Not Setosa
119,6.0,2.2,5.0,1.500000,Virginica,Not Setosa
120,6.9,3.2,5.7,2.300000,Virginica,Not Setosa
121,5.6,2.8,4.9,2.000000,Virginica,Not Setosa
122,7.7,2.8,6.7,2.000000,Virginica,Not Setosa
123,6.3,2.7,4.9,1.800000,Virginica,Not Setosa
124,6.7,3.3,5.7,2.100000,Virginica,Not Setosa
125,7.2,3.2,6.0,1.800000,Virginica,Not Setosa
126,6.2,2.8,4.8,1.800000,Virginica,Not Setosa
127,6.1,3.0,4.9,1.800000,Virginica,Not Setosa
128,6.4,2.8,5.6,2.100000,Virginica,Not Setosa
129,7.2,3.0,5.8,1.600000,Virginica,Not Setosa
130,7.4,2.8,6.1,1.900000,Virginica,Not Setosa
131,7.9,3.8,6.4,2.000000,Virginica,Not Setosa
132,6.4,2.8,5.6,2.200000,Virginica,Not Setosa
133,6.3,2.8,5.1,1.500000,Virginica,Not Setosa
134,6.1,2.6,5.6,1.400000,Virginica,Not Setosa
135,7.7,3.0,6.1,2.300000,Virginica,Not Setosa
136,6.3,3.4,5.6,2.400000,Virginica,Not Setosa
137,6.4,3.1,5.5,1.800000,Virginica,Not Setosa
138,6.0,3.0,4.8,1.800000,Virginica,Not Setosa
139,6.9,3.1,5.4,2.100000,Virginica,Not Setosa
140,6.7,3.1,5.6,2.400000,Virginica,Not Setosa
141,6.9,3.1,5.1,2.300000,Virginica,Not Setosa
142,5.8,2.7,5.1,1.900000,Virginica,Not Setosa
143,6.8,3.2,5.9,2.300000,Virginica,Not Setosa
144,6.7,3.3,5.7,2.500000,Virginica,Not Setosa
145,6.7,3.0,5.2,2.300000,Virginica,Not Setosa
146,6.3,2.5,5.0,1.900000,Virginica,Not Setosa
147,6.5,3.0,5.2,2.000000,Virginica,Not Setosa
148,6.2,3.4,5.4,2.300000,Virginica,Not Setosa
149,5.9,3.0,5.1,1.800000,Virginica,Not Setosa
150,5.9,3.0,5.1,1.800000,Virginica,Not Setosa
151,5.9,3.0,5.1,1.800000,Virginica,Not Setosa
152,5.9,3.0,5.1,1.800000,Virginica,Not Setosa

In [15]:
#Find maximum sepal_width by variety using SQL
max_variety = sqldf("""Select variety,max([sepal.width]) as max_sepal From iris group by variety""")
max_variety

      variety  max_sepal
0      Setosa        4.4
1  Versicolor        3.4
2   Virginica        3.8

In [14]:
max_variety2 = iris.pivot_table(columns = 'variety', values='sepal.width', aggfunc='max')
max_variety2

variety      Setosa  Versicolor  Virginica
sepal.width     4.4         3.4        3.8

In [16]:
max_variety3 = max_variety.pivot(columns = 'variety', values='max_sepal')
max_variety3

variety  Setosa  Versicolor  Virginica
0           4.4         NaN        NaN
1           NaN         3.4        NaN
2           NaN         NaN        3.8